// docs/src/components/ui/button.tsx
import { Button as ButtonPrimitive } from "@base-ui/react/button"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "focus-visible:border-ring focus-visible:ring-ring/30 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:aria-invalid:border-destructive/50 rounded-md border border-transparent bg-clip-padding text-xs/relaxed font-medium focus-visible:ring-2 aria-invalid:ring-2 [&_svg:not([class*='size-'])]:size-4 inline-flex items-center justify-center whitespace-nowrap transition-[color,background-color,border-color,box-shadow,opacity,transform] duration-[var(--duration-press)] ease-[var(--ease-out)] active:scale-[0.97] disabled:pointer-events-none disabled:opacity-50 disabled:active:scale-100 motion-reduce:transition-colors motion-reduce:active:scale-100 [&_svg]:pointer-events-none shrink-0 [&_svg]:shrink-0 outline-none group/button select-none",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/80",
        outline:
          "border-border dark:bg-input/30 hover:bg-input/50 hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary/80 aria-expanded:bg-secondary aria-expanded:text-secondary-foreground",
        ghost:
          "hover:bg-muted hover:text-foreground dark:hover:bg-muted/50 aria-expanded:bg-muted aria-expanded:text-foreground",
        destructive:
          "bg-destructive/10 hover:bg-destructive/20 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/20 text-destructive focus-visible:border-destructive/40 dark:hover:bg-destructive/30",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default:
          "h-7 gap-1 px-2 text-xs/relaxed has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3.5",
        xs: "h-5 gap-1 rounded-sm px-2 text-[0.625rem] has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-2.5",
        sm: "h-6 gap-1 px-2 text-xs/relaxed has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3",
        lg: "h-8 gap-1 px-2.5 text-xs/relaxed has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2 [&_svg:not([class*='size-'])]:size-4",
        icon: "size-7 [&_svg:not([class*='size-'])]:size-3.5",
        "icon-xs": "size-5 rounded-sm [&_svg:not([class*='size-'])]:size-2.5",
        "icon-sm": "size-6 [&_svg:not([class*='size-'])]:size-3",
        "icon-lg": "size-8 [&_svg:not([class*='size-'])]:size-4",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Button({
  className,
  variant = "default",
  size = "default",
  ...props
}: ButtonPrimitive.Props & VariantProps<typeof buttonVariants>) {
  return (
    <ButtonPrimitive
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button, buttonVariants }

// chowser-electrobun/src/views/shared/components/Button.svelte
<script lang="ts">
  interface ButtonProps {
    variant?: 'primary' | 'secondary' | 'ghost';
    size?: 'sm' | 'md' | 'lg';
    disabled?: boolean;
    type?: 'button' | 'submit' | 'reset';
    onclick?: () => void;
  }

  let {
    variant = 'primary',
    size = 'md',
    disabled = false,
    type = 'button',
    onclick
  } = $props<ButtonProps>();
</script>

<button
  {type}
  {disabled}
  on:click={onclick}
  class="button button--{variant} button--{size}"
>
  <slot />
</button>

<style>
  .button {
    font-family: var(--font-family-system);
    font-weight: var(--font-weight-medium);
    border: none;
    cursor: pointer;
    border-radius: var(--radius-md);
    transition: all 0.2s ease;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    white-space: nowrap;
  }

  /* Sizes */
  .button--sm {
    font-size: var(--font-size-sm);
    padding: var(--spacing-2) var(--spacing-3);
    height: 32px;
  }

  .button--md {
    font-size: var(--font-size-base);
    padding: var(--spacing-3) var(--spacing-4);
    height: 40px;
  }

  .button--lg {
    font-size: var(--font-size-lg);
    padding: var(--spacing-4) var(--spacing-6);
    height: 48px;
  }

  /* Variants */
  .button--primary {
    background-color: var(--color-accent);
    color: white;
  }

  .button--primary:hover:not(:disabled) {
    background-color: var(--color-accent-hover);
  }

  .button--primary:active:not(:disabled) {
    background-color: var(--color-accent-pressed);
  }

  .button--secondary {
    background-color: var(--color-control-background);
    color: var(--color-text-primary);
    border: 1px solid var(--color-control-border);
  }

  .button--secondary:hover:not(:disabled) {
    background-color: var(--color-background-secondary);
    border-color: var(--color-separator);
  }

  .button--secondary:active:not(:disabled) {
    background-color: var(--color-background-tertiary);
  }

  .button--ghost {
    background-color: transparent;
    color: var(--color-accent);
  }

  .button--ghost:hover:not(:disabled) {
    background-color: var(--color-glass-light);
  }

  .button--ghost:active:not(:disabled) {
    background-color: var(--color-control-background);
  }

  /* Disabled state */
  .button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
</style>
